config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "home#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :lists do
    resources :expenses
  end

  get '/categories/:id', to: 'category#show', as: 'category_search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :expenses
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :list
  belongs_to :category

  validates_presence_of :name, length: { in: 2..100 }
  validates_presence_of :amount, numericality: { only_integer: true }
  validates_presence_of :cost

  def total_cost
    (cost * amount).round(2)
  end
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :expenses, dependent: :destroy

  validates_presence_of :name, length: { in: 2..100 }

  def total_cost
    total_cost = 0
    self.expenses.each { |expense| total_cost += expense.cost * expense.amount }

    total_cost.round(2)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :lists, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  before_action :set_category, only: %i[ show ]

  # GET /category/1
  def show
    @user_list_ids = List.where("user_id = #{current_user.id}").pluck(:id)
    @expenses = Expense
                  .where("category_id = #{@category.id}")
                  .select{ |expense| expense if @user_list_ids.include?(expense.list_id) }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: %i[ show edit update destroy ]
  before_action :set_list, only: %i[ show create edit update destroy ]

  # GET /expenses or /expenses.json
  def index
    @expenses = Expense.all
  end

  # GET /expenses/1 or /expenses/1.json
  def show
  end

  # GET list/{:list_id}/expenses/new
  def new
    @list = List.find(params[:list_id])
    @categories = Category.all
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST list/{:list_id}/expenses or /expenses.json
  def create
    @expense = @list.expenses.create(expense_params)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to list_path(@list), notice: "Expense was successfully created." }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { redirect_to list_path(@list), notice: "Expense has not been created." }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1 or /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to expense_url(@expense), notice: "Expense was successfully updated." }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE list/{:list_id}/expenses/1 
  def destroy
    @expense.destroy
    redirect_to list_path(@list)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:list_id])
    end
    
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def expense_params
      params.require(:expense).permit(:name, :amount, :cost, :list_id, :category_id)
    end
end

app/controllers/home_controller.rb
# frozen_string_literal: true
class HomeController < ApplicationController
  def index
    @lists = List.all
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /lists or /lists.json
  def index
    @lists = List.where("user_id = #{current_user.id}")
  end

  # GET /lists/1 or /lists/1.json
  def show
    @expenses = Expense.where("list_id = #{@list.id}")
    @categories = Category.all
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists or /lists.json
  def create
    @list = List.new(list_params)
    @list.user_id = current_user.id

    respond_to do |format|
      if @list.save
        format.html { redirect_to list_url(@list), notice: "List was successfully created." }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1 or /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to list_url(@list), notice: "List was successfully updated." }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1 or /lists/1.json
  def destroy
    @list.destroy

    respond_to do |format|
      format.html { redirect_to lists_url, notice: "List was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:name, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link_active?(link_name)
    "active" if controller_name == link_name
  end    
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
  def users_list
    current_user.id == @list.user_id
  end
  alias_method :users_list?, :users_list
end

app/views/category/show.html.erb
<%= link_to 'Back', url_for(:back), class: "btn btn-sm btn-secondary" %>

<div class="d-flex justify-content-between my-2">
  <h4 class="mt-3">Your spendings on <%= @category.name %></h4>

</div>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Category</th>
      <th scope="col">Amount</th>
      <th scope="col">Cost of Item</th>
      <th scope="col">Total Cost</th>
    </tr>
  </thead>
  <tbody>
    <% @expenses.each_with_index do |expense, index| %>
      <tr class="align-middle">
        <th scope="row"><%= index + 1 %></th>
        <td><%= expense.name %></td>
        <td><%= @category.name %></td>
        <td><%= expense.amount %></td>
        <td><%= expense.cost %></td>
        <td><%= expense.total_cost %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/expenses/_add_expense_modal.html.erb
<div class="modal" id="new-expense-modal" tabindex="-1" aria-labelledby="new-expense-modal-label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header border-bottom-0 justify-content-start">
        <button type="button" class="close-modal-btn btn-close mx-0" data-bs-dismiss="modal" aria-label="Close">
        </button>
        <div class="d-flex w-100 justify-content-center">
          <h3 class="mb-0">New Expense</h3>
        </div>
      </div>
      <div class="modal-body pb-4">
        <%= render "expenses/form", expense: Expense.new %>
      </div>
    </div>
  </div>
</div>

app/views/expenses/_delete_expense_modal.html.erb
<div class="modal fade" id=<%= "delete-expense-#{expense.id}-modal" %> tabindex="-1" role="dialog" aria-labelledby="delete-expense-modal-label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body my-2">
        <span class="fs-5 p-2">Do you want to delete this expense?</span>
      </div>
      <div class="modal-footer">
        <%= button_to "Delete", [@list, expense], method: :delete, class: "btn btn-sm btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/expenses/_expense.html.erb
<div id="<%= dom_id expense %>">
  <p>
    <strong>Name:</strong>
    <%= expense.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= expense.amount %>
  </p>

  <p>
    <strong>Cost:</strong>
    <%= expense.cost %>
  </p>

  <p>
    <strong>List:</strong>
    <%= expense.list_id %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= expense.category_id %>
  </p>

</div>

app/views/expenses/_form.html.erb
<div class="card-body">
  <%= form_with(model: [@list, expense]) do |form| %>
    <% if expense.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

        <ul>
          <% expense.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-3">
      <div class="form-label fw-bold fs-6">
        <%= form.label :name, style: "display: block" %>
      </div>
      <%= form.text_field :name, class: "form-control", :required => "required" %>
    </div>

    <div class="mb-3">
      <div class="form-label fw-bold fs-6">
        <%= form.label :amount, style: "display: block" %>
      </div>
      <%= form.number_field :amount, :min => 1, class: "form-control", :required => "required" %>
    </div>

    <div class="mb-3">
      <div class="form-label fw-bold fs-6">
        <%= form.label :cost, style: "display: block" %>
      </div>
      <%= form.number_field :cost,
                            :value => (number_with_precision(form.object.cost, :precision => 2) || 0),
                            :step => "0.01",
                            :min => 0,
                            class: "form-control" %>
    </div>

    <div class="mb-3">
      <div class="form-label fw-bold fs-6">
        <%= form.label :category_id, style: "display: block" %>
      </div>
      <%= form.collection_select :category_id, @categories, :id, :name, {}, { class: "form form-group form-select" } %>
    </div>

    <div class="text-center">
      <%= form.submit :class => "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render "form", expense: @expense %>

<br>

<div>
  <%= link_to "Show this expense", @expense %> |
  <%= link_to "Back to expenses", expenses_path %>
</div>

app/views/expenses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Expenses</h1>

<div id="expenses">
  <% @expenses.each do |expense| %>
    <%= render expense %>
    <p>
      <%= link_to "Show this expense", expense %>
    </p>
  <% end %>
</div>

<%= link_to "New expense", new_expense_path %>

app/views/expenses/new.html.erb
<div class="offset-3 mb-3">
  <%= link_to 'Back', url_for(:back), class: "btn btn-sm btn-secondary" %>
</div>

<div class="card offset-3 col-6">
  <div class="card-header text-center">
    <h2 class="mt-2">New Expense</h2>
  </div>

  <%= render "form", expense: @expense %>
</div>

app/views/expenses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @expense %>

<div>
  <%= link_to "Edit this expense", edit_expense_path(@expense) %> |
  <%= link_to "Back to expenses", expenses_path %>

  <%= button_to "Destroy this expense", @expense, method: :delete %>
</div>

app/views/home/index.html.erb
<main class="container">
  <h2 class="text-center my-2">Stored Lists</h2>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Total Cost</th>
        <th scope="col">Author</th>
      </tr>
    </thead>
    <tbody>
      <% @lists.each_with_index do |list, index| %>
        <tr 
          class=<% if current_user.present? %>
            <%= current_user.id == list.user_id ? 'bg-warning' : '' %>
          <% end %>
        >
          <th scope="row"><%= index + 1 %></th>
          <td class="col-5">
            <%= link_to(list) do %>
              <%= list.name %>
            <% end %>
          </td>
          <td><%= list.total_cost %></td>
          <td class="col-3"><%= list.user.email %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</main>

app/views/layouts/_alerts.html.erb
<div class="text-center my-4">
  <p class="text-success"><%= notice %></p>
  <p class="text-danger"><%= alert %></p>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" aria-label="Offcanvas navbar large">
  <div class="container-fluid">
    <%= link_to "Expense Tracker", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar2" aria-controls="offcanvasNavbar2">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasNavbar2" aria-labelledby="offcanvasNavbar2Label">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasNavbar2Label">Offcanvas</h5>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <%= link_to "Home", root_path, class: "nav-link #{nav_link_active?('home')}" %>
          <li class="nav-item">
            <%= link_to "Your Lists", lists_path, class: "nav-link #{nav_link_active?('lists')}" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Profile
            </a>
            <ul class="dropdown-menu">
              <% if current_user.present? %>
                <%= link_to "New list", new_list_path, class: "dropdown-item" %>
                <li><hr class="dropdown-divider"></li>
                <%= link_to "Logout", destroy_user_session_path, data: {turbo_method: "delete"}, class: "dropdown-item" %>
              <% else %>
                <%= link_to "Sign Up", new_user_registration_path, class: "dropdown-item" %>
                <li><hr class="dropdown-divider"></li>
                <%= link_to "Login", new_user_session_path, class: "dropdown-item" %>
              <% end %>
            </ul>
          </li>
        </ul>
        <form class="d-flex mt-3 mt-lg-0" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Expense Tracking App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render partial: 'layouts/navbar' %>
    <%= render partial: 'layouts/alerts' %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_delete_list_modal.html.erb
<div class="modal fade" id=<%= "delete-list-#{list.id}-modal" %> tabindex="-1" role="dialog" aria-labelledby="delete-list-modal-label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body my-2">
        <span class="fs-5 p-2">Remove this list?</span>
      </div>
      <div class="modal-footer">
        <%= button_to "Remove", list, method: :delete, class: "btn btn-sm btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/lists/_edit_list_modal.html.erb
<div class="modal" id="edit-list-modal" tabindex="-1" aria-labelledby="edit-list-modal-label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header border-bottom-0">
        <div class="d-flex w-100 justify-content-center">
          <h3 class="mb-0">Edit list</h3>
        </div>
      </div>
      <div class="modal-body pb-3">
        <%= render "lists/form", list: @list %>
      </div>
    </div>
  </div>
</div>

app/views/lists/_form.html.erb
<%= form_with(model: list) do |form| %>
  <% if list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <div class="form-label fw-bold fs-6">
      <%= form.label :name, style: "display: block" %>
    </div>
    <%= form.text_field :name, class: "form-control", :required => "required" %>
  </div>

  <div class="text-center">
    <%= form.submit :class => "btn btn-success" %>
  </div>
<% end %>

app/views/lists/_list.html.erb
<div id="<%= dom_id list %>" class="d-flex my-3">
  <h4><%= list.name %></h4>
  <p><%= list.total_cost %></p>
</div>

app/views/lists/edit.html.erb
<div class="offset-3 mb-3">
  <%= link_to 'Back', url_for(:back), class: "btn btn-sm btn-secondary" %>
</div>

<div class="card offset-3 col-6">
  <div class="card-header text-center">
    <h2 class="mt-2">Edit List</h2>
  </div>

  <div class="card-body">
    <%= render "form", list: @list %>
  </div>
</div>

app/views/lists/index.html.erb
<h2 class="text-center my-2">Your Lists</h2>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Total Cost</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @lists.each_with_index do |list, index| %>
      <tr class="align-middle">
        <th scope="row"><%= index + 1 %></th>
        <td>
          <h5 class="mb-0">
            <%= link_to(list) do %>
              <%= list.name %>
            <% end %>
          </h5>
        </td>
        <td><%= list.total_cost %></td>
        <td class="col-1">
          <%= button_tag "Delete", data: { "bs-toggle": "modal", "bs-target": "#delete-list-#{list.id}-modal" }, class: "btn btn-sm btn-danger" %>
          <%= render partial: "lists/delete_list_modal", locals: { list: list } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New list", new_list_path, class: "btn btn-sm btn-success" %>

app/views/lists/new.html.erb
<div class="offset-3 mb-3">
  <%= link_to 'Back', url_for(:back), class: "btn btn-sm btn-secondary" %>
</div>

<div class="card offset-3 col-6">
  <div class="card-header text-center">
    <h2 class="mt-2">New List</h2>
  </div>

  <div class="card-body">
    <%= render "form", list: @list %>
  </div>
</div>

app/views/lists/show.html.erb
<%= link_to "Back", root_path, class: "btn btn-sm btn-secondary" %>

<div class="d-flex justify-content-between my-2">
  <h4 class="mt-3"><%= @list.name %></h4>

  <% if users_list? %>
    <div class="d-flex h-50">
      <%= button_tag "Edit List", data: { "bs-toggle": "modal", "bs-target": "#edit-list-modal" }, class: "btn btn-sm btn-primary me-2" %>
      <%= render partial: "lists/edit_list_modal" %>

      <%= button_tag "Remove List", data: { "bs-toggle": "modal", "bs-target": "#delete-list-#{@list.id}-modal" }, class: "btn btn-sm btn-danger" %>
      <%= render partial: "lists/delete_list_modal", locals: { list: @list } %>
    </div>
  <% end %>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Category</th>
      <th scope="col">Amount</th>
      <th scope="col">Cost of Item</th>
      <th scope="col">Total Cost</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @expenses.each_with_index do |expense, index| %>
      <tr class="align-middle">
        <th scope="row"><%= index + 1 %></th>
        <td><%= expense.name %></td>
        <td>
          <% if users_list? %>
            <%= link_to "#{expense.category.name}", category_search_path(expense.category.id) %>
          <% else %>
            <%= expense.category.name %>
          <% end %>
        </td>
        <td><%= expense.amount %></td>
        <td><%= expense.cost %></td>
        <td><%= expense.total_cost %></td>
        <td class="col-1">
          <% if users_list? %>
            <%= button_tag "X", data: { "bs-toggle": "modal", "bs-target": "#delete-expense-#{expense.id}-modal" }, class: "btn btn-sm btn-danger" %>
          
            <%= render partial: "expenses/delete_expense_modal", locals: { expense: expense } %>
          <% end %>
        </td>
      </tr>
    <% end %>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <th scope="row">Total cost:</th>
      <td><%= @list.total_cost %></td>
      <td></td>
    </tr>
  </tbody>
</table>

<!-- Add expense modal -->
<% if users_list? %>
  <%= button_tag "New expense", data: { "bs-toggle": "modal", "bs-target": "#new-expense-modal" }, class: "btn btn-sm btn-primary p-2 mt-2 mb-4" %>

  <%= render partial: "expenses/add_expense_modal" %>
<% end %>